### ISSUE TITLE
Animation UI issue on best seller section on homepage- mobile UI

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Edward-Internal-may-26th-#12]
Bug - showing spacing between image after appearing animation.
Exp - Should not show spacing on best seller section images.
Ref Link - https://drive.google.com/file/d/1o_vU2WJXUqJghZPSa38cubj9RgsoIoZ4/view

**Comment by ui-deepanshushukla** [comment]
in progress

**Comment by ankitcedcoss** [comment]
Bug Fixed
