### ISSUE TITLE
social links opening on same page

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Edward-Internal-may-26th-#19]
Bug - On clicking on social links then its showing on same tab on browser.
Exp - It should be open on new tab when user click on social link.
Ref Link - https://drive.google.com/file/d/1m9WWTVQzZ9nqRixlLQI5JiOheaeFK9wR/view

**Comment by devSuneel** [comment]
resolved

**Comment by ankitcedcoss** [comment]
Bug Fixed
