### ISSUE TITLE
Validation issue on newsletter section.

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Edward-Internal-may-26th-#8]
Bug - html validation not showing on entering invalid email or leaving blank field.
Exp - Should show validation error on invalid email or blank field.
Ref Link - https://drive.google.com/file/d/1-gUrPRcPi5nKdCstUzTZDUsjc_s28fq8/view

**Comment by devSuneel** [comment]
resolved

**Comment by ankitcedcoss** [comment]
Bug Fixed
